"""Scheduler backend interface and scoped artifact reconciliation."""

from __future__ import annotations

import difflib
import os
import secrets
import sys
from abc import ABC, abstractmethod
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import ClassVar

from .. import paths, records
from ..commands import CommandResult, CommandRunner, SubprocessRunner
from ..spec import MachinePolicy, TaskSpec

CREATE, UPDATE, DELETE, UNCHANGED = "create", "update", "delete", "unchanged"
GENERATED_HEADER = "GENERATED BY automationctl - DO NOT EDIT"


@dataclass(frozen=True)
class FileChange:
    action: str
    path: Path
    diff: str = ""

    @property
    def changed(self) -> bool:
        return self.action != UNCHANGED


@dataclass(frozen=True)
class ReconcilePlan:
    changes: tuple[FileChange, ...] = ()

    @property
    def changed(self) -> tuple[FileChange, ...]:
        return tuple(item for item in self.changes if item.changed)

    @property
    def has_changes(self) -> bool:
        return bool(self.changed)


@dataclass(frozen=True)
class HealthCheck:
    name: str
    ok: bool
    detail: str


def _diff(name: str, before: str, after: str) -> str:
    return "".join(
        difflib.unified_diff(
            before.splitlines(keepends=True),
            after.splitlines(keepends=True),
            fromfile=f"a/{name}",
            tofile=f"b/{name}",
        )
    )


class Backend(ABC):
    name: ClassVar[str] = ""

    def __init__(
        self,
        *,
        unit_dir: Path,
        runner: CommandRunner,
        executable: str,
        config_home: Path,
        state_home: Path,
        state_dir: Path,
    ) -> None:
        self.unit_dir, self.runner, self.executable = unit_dir, runner, executable
        self.config_home, self.state_home, self.state_dir = config_home, state_home, state_dir

    @abstractmethod
    def task_filenames(self, task: TaskSpec) -> tuple[str, ...]: ...

    @abstractmethod
    def possible_task_filenames(self, name: str) -> tuple[str, ...]: ...

    @abstractmethod
    def desired_task_files(self, task: TaskSpec) -> dict[str, str]: ...

    @abstractmethod
    def desired_catchup_files(self, policy: MachinePolicy) -> dict[str, str]: ...

    def exec_argv(self, task: TaskSpec, *, jitter: bool = False) -> list[str]:
        argv = [self.executable, "exec"]
        if jitter:
            argv.append("--jitter")
        return [*argv, task.name]

    def catchup_argv(self) -> list[str]:
        return [self.executable, "catch-up"]

    def plan(self, desired: Mapping[str, str], scope: Sequence[str]) -> ReconcilePlan:
        changes: list[FileChange] = []
        for name in sorted(set(scope) | set(desired)):
            path = self.unit_dir / name
            try:
                before = path.read_text(encoding="utf-8")
            except FileNotFoundError:
                before = None
            if name not in desired:
                if before is not None:
                    changes.append(FileChange(DELETE, path, _diff(name, before, "")))
            elif before is None:
                changes.append(FileChange(CREATE, path, _diff(name, "", desired[name])))
            elif before != desired[name]:
                changes.append(FileChange(UPDATE, path, _diff(name, before, desired[name])))
            else:
                changes.append(FileChange(UNCHANGED, path))
        return ReconcilePlan(tuple(changes))

    def apply(self, plan: ReconcilePlan, desired: Mapping[str, str]) -> list[CommandResult]:
        removals = [item.path.name for item in plan.changes if item.action == DELETE]
        results = self.deactivate(removals) if removals else []
        if any(not result.ok for result in results):
            return results
        for name in removals:
            (self.unit_dir / name).unlink(missing_ok=True)
        writes = [item for item in plan.changes if item.action in {CREATE, UPDATE}]
        if writes:
            self.unit_dir.mkdir(parents=True, exist_ok=True)
            for item in writes:
                temporary = item.path.with_name(
                    f".{item.path.name}.{os.getpid()}.{secrets.token_hex(4)}.tmp"
                )
                descriptor = os.open(
                    temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, records.PRIVATE_FILE_MODE
                )
                try:
                    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
                        handle.write(desired[item.path.name])
                        handle.flush()
                        os.fsync(handle.fileno())
                    temporary.replace(item.path)
                except OSError:
                    temporary.unlink(missing_ok=True)
                    raise
        return results

    def rewritten(self, plan: ReconcilePlan) -> set[str]:
        return {item.path.name for item in plan.changes if item.action in {CREATE, UPDATE}}

    def reload(self) -> list[CommandResult]:
        return []

    @abstractmethod
    def activate(
        self, task: TaskSpec, desired: Mapping[str, str], rewritten: set[str]
    ) -> list[CommandResult]: ...

    @abstractmethod
    def activate_catchup(
        self, desired: Mapping[str, str], rewritten: set[str]
    ) -> list[CommandResult]: ...

    @abstractmethod
    def deactivate(self, filenames: Sequence[str]) -> list[CommandResult]: ...

    @abstractmethod
    def submit(self, task: TaskSpec) -> list[CommandResult]: ...

    @abstractmethod
    def pause(self, task: TaskSpec) -> list[CommandResult]: ...

    @abstractmethod
    def resume(self, task: TaskSpec) -> list[CommandResult]: ...

    @abstractmethod
    def enabled(self, task: TaskSpec) -> bool | None: ...

    @abstractmethod
    def follow_argv(self, task: TaskSpec) -> tuple[str, ...] | None: ...

    def health(self) -> list[HealthCheck]:
        return []

    def catchup_health(self, tasks: Sequence[TaskSpec], policy: MachinePolicy) -> list[HealthCheck]:
        return []


def default_backend_name(env: Mapping[str, str] | None = None) -> str:
    values = os.environ if env is None else env
    forced = values.get(paths.BACKEND_ENV)
    if forced:
        if forced not in {"systemd", "launchd"}:
            raise ValueError(f"unknown backend: {forced}")
        return forced
    return "launchd" if sys.platform == "darwin" else "systemd"


def create(
    name: str,
    *,
    unit_dir: Path | None = None,
    env: Mapping[str, str] | None = None,
    runner: CommandRunner | None = None,
    executable: str | None = None,
) -> Backend:
    values = os.environ if env is None else env
    resolved_unit_dir = unit_dir or paths.default_unit_dir(name, values)
    resolved_runner = runner or SubprocessRunner()
    resolved_executable = executable or paths.executable(values)
    resolved_config_home = paths.config_home(values)
    resolved_state_dir = paths.state_dir(values)
    if name == "systemd":
        from .systemd import SystemdBackend

        return SystemdBackend(
            unit_dir=resolved_unit_dir,
            runner=resolved_runner,
            executable=resolved_executable,
            config_home=resolved_config_home,
            state_home=resolved_state_dir.parent,
            state_dir=resolved_state_dir,
        )
    if name == "launchd":
        from .launchd import LaunchdBackend

        return LaunchdBackend(
            unit_dir=resolved_unit_dir,
            runner=resolved_runner,
            executable=resolved_executable,
            config_home=resolved_config_home,
            state_home=resolved_state_dir.parent,
            state_dir=resolved_state_dir,
        )
    raise ValueError(f"unknown backend: {name}")
