"""The scheduler backend interface, extracted from two real implementations.

A backend owns three things: what files it generates, how those files are
reconciled against the filesystem, and which control commands assert the
desired state. Everything else — environment, locks, timeouts, records,
notification — belongs to the wrapper and is identical on both platforms.
"""

from __future__ import annotations

import difflib
import os
import sys
from abc import ABC, abstractmethod
from collections.abc import Collection, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import ClassVar

from .. import paths
from ..commands import CommandResult, CommandRunner, SubprocessRunner
from ..config import Automations
from ..errors import BackendError
from ..spec import TaskSpec

CREATE = "create"
UPDATE = "update"
DELETE = "delete"
UNCHANGED = "unchanged"

GENERATED_HEADER = "GENERATED BY automationctl - DO NOT EDIT"


@dataclass(frozen=True)
class FileChange:
    """One reconciliation step against the generated-unit directory."""

    action: str
    path: Path
    diff: str = ""

    @property
    def changed(self) -> bool:
        return self.action != UNCHANGED


@dataclass(frozen=True)
class ReconcilePlan:
    """The full set of file operations ``install`` would perform."""

    changes: tuple[FileChange, ...] = ()

    @property
    def changed(self) -> tuple[FileChange, ...]:
        return tuple(item for item in self.changes if item.changed)

    @property
    def has_changes(self) -> bool:
        return bool(self.changed)


@dataclass(frozen=True)
class HealthCheck:
    """One ``doctor`` probe result."""

    name: str
    ok: bool
    detail: str


def unified_diff(name: str, before: str, after: str) -> str:
    """Render a unified diff between two versions of a generated file."""
    lines = difflib.unified_diff(
        before.splitlines(keepends=True),
        after.splitlines(keepends=True),
        fromfile=f"a/{name}",
        tofile=f"b/{name}",
    )
    return "".join(lines)


class Backend(ABC):
    """A platform scheduler that automationctl compiles task specs into."""

    name: ClassVar[str] = ""

    def __init__(
        self,
        *,
        unit_dir: Path,
        runner: CommandRunner,
        executable: str,
        manifest_path: Path,
        state_dir: Path,
    ) -> None:
        self.unit_dir = unit_dir
        self.runner = runner
        self.executable = executable
        self.manifest_path = manifest_path
        # Required, never defaulted: a backend that quietly reached for the
        # real state directory would be the one way a test could write to the
        # user's own state.
        self.state_dir = state_dir

    # -- rendering ---------------------------------------------------------

    @abstractmethod
    def is_managed(self, filename: str) -> bool:
        """Return whether a filename belongs to this tool."""

    @abstractmethod
    def task_filenames(self, task: TaskSpec) -> tuple[str, ...]:
        """Return the filenames one task generates."""

    @abstractmethod
    def desired_files(self, automations: Automations, tasks: Sequence[TaskSpec]) -> dict[str, str]:
        """Render every generated file for the given tasks."""

    def exec_argv(self, task: TaskSpec, *, host: str, jitter: bool = False) -> list[str]:
        """Return the argv a unit or plist uses to start one task."""
        argv = [
            self.executable,
            "exec",
            "--manifest",
            str(self.manifest_path),
            "--host",
            host,
        ]
        if jitter:
            argv.append("--jitter")
        argv.append(task.name)
        return argv

    def catchup_argv(self, *, host: str) -> list[str]:
        """Return the argv a generated catch-up trigger starts."""
        return [
            self.executable,
            "catch-up",
            "--manifest",
            str(self.manifest_path),
            "--host",
            host,
        ]

    # -- reconciliation ----------------------------------------------------

    def existing_files(self) -> dict[str, str]:
        """Return the managed files currently on disk, filename to content."""
        if not self.unit_dir.is_dir():
            return {}
        found: dict[str, str] = {}
        for entry in sorted(self.unit_dir.iterdir()):
            if entry.is_file() and self.is_managed(entry.name):
                found[entry.name] = entry.read_text(encoding="utf-8")
        return found

    def plan(self, desired: Mapping[str, str]) -> ReconcilePlan:
        """Compare desired against on-disk state without touching anything."""
        existing = self.existing_files()
        changes: list[FileChange] = []
        for filename in sorted(set(desired) | set(existing)):
            path = self.unit_dir / filename
            if filename not in existing:
                changes.append(
                    FileChange(CREATE, path, unified_diff(filename, "", desired[filename]))
                )
            elif filename not in desired:
                changes.append(
                    FileChange(DELETE, path, unified_diff(filename, existing[filename], ""))
                )
            elif existing[filename] != desired[filename]:
                changes.append(
                    FileChange(
                        UPDATE,
                        path,
                        unified_diff(filename, existing[filename], desired[filename]),
                    )
                )
            else:
                changes.append(FileChange(UNCHANGED, path))
        return ReconcilePlan(changes=tuple(changes))

    def apply(self, plan: ReconcilePlan, desired: Mapping[str, str]) -> list[CommandResult]:
        """Write, update, and garbage-collect generated files."""
        results: list[CommandResult] = []
        removals = [item for item in plan.changes if item.action == DELETE]
        if removals:
            results.extend(self.deactivate([item.path.name for item in removals]))
            for item in removals:
                item.path.unlink(missing_ok=True)
        writes = [item for item in plan.changes if item.action in {CREATE, UPDATE}]
        if writes:
            self.unit_dir.mkdir(parents=True, exist_ok=True)
            for item in writes:
                item.path.write_text(desired[item.path.name], encoding="utf-8")
        return results

    # -- substrate operations ---------------------------------------------

    def reload(self) -> list[CommandResult]:
        """Tell the scheduler to re-read generated files."""
        return []

    @abstractmethod
    def activate(
        self,
        automations: Automations,
        tasks: Sequence[TaskSpec],
        desired: Mapping[str, str] = MappingProxyType({}),
        rewritten: Collection[str] = (),
    ) -> list[CommandResult]:
        """Enable and start whatever the given tasks require.

        ``desired`` is the rendered content of every generated file, and
        ``rewritten`` names the files this reconcile just created or updated.
        A backend whose reload is disruptive — launchd must unload an agent
        before it can load a new definition — reloads only what those two
        signals mark, so an install that changes one task never kills another
        task's running job.

        Both signals are needed. Recorded activation catches a file whose
        activation never landed, which a file diff cannot see because the file
        was already written. ``rewritten`` catches a file that drifted on disk
        and was loaded by someone else, which the activation record cannot see
        because it still matches what we last activated.
        """

    @abstractmethod
    def deactivate(self, filenames: Sequence[str]) -> list[CommandResult]:
        """Stop and disable the units behind the given generated files."""

    @abstractmethod
    def submit(self, task: TaskSpec) -> list[CommandResult]:
        """Start one task in the background, now, through the substrate."""

    @abstractmethod
    def pause(self, task: TaskSpec) -> list[CommandResult]:
        """Temporarily stop a task's schedule."""

    @abstractmethod
    def resume(self, task: TaskSpec) -> list[CommandResult]:
        """Undo :meth:`pause`."""

    @abstractmethod
    def enabled(self, task: TaskSpec) -> bool | None:
        """Return whether the task's schedule is active, or ``None`` if unknown."""

    @abstractmethod
    def follow_argv(self, task: TaskSpec) -> tuple[str, ...] | None:
        """Return the argv that follows this task's live logs, if supported."""

    @abstractmethod
    def health(self) -> list[HealthCheck]:
        """Run read-only probes for ``doctor``."""

    def catchup_health(
        self, automations: Automations, tasks: Sequence[TaskSpec]
    ) -> list[HealthCheck]:
        """Report whether this host's catch-up triggers are installed and usable.

        Separate from :meth:`health` because it needs the desired state, not
        only the substrate: whether a trigger is missing depends on whether
        this host selects anything for it to recover.
        """
        return []


BACKEND_NAMES = ("systemd", "launchd")


def default_backend_name(env: Mapping[str, str] | None = None) -> str:
    """Return the backend for this host, honouring the environment override."""
    values = os.environ if env is None else env
    override = values.get(paths.BACKEND_ENV)
    if override:
        if override not in BACKEND_NAMES:
            raise BackendError(
                f"unknown backend: {override} (expected one of {', '.join(BACKEND_NAMES)})"
            )
        return override
    return "launchd" if sys.platform == "darwin" else "systemd"


def create(
    name: str,
    *,
    manifest_path: Path,
    unit_dir: Path | None = None,
    runner: CommandRunner | None = None,
    executable: str | None = None,
    env: Mapping[str, str] | None = None,
    uid: int | None = None,
    state_dir: Path | None = None,
) -> Backend:
    """Build a backend instance, filling every unset argument from the environment."""
    from .launchd import LaunchdBackend
    from .systemd import SystemdBackend

    values = os.environ if env is None else env
    if name not in BACKEND_NAMES:
        raise BackendError(f"unknown backend: {name} (expected one of {', '.join(BACKEND_NAMES)})")
    kwargs = {
        "unit_dir": unit_dir if unit_dir is not None else paths.default_unit_dir(name, values),
        "runner": runner if runner is not None else SubprocessRunner(),
        "executable": executable if executable is not None else paths.executable(values),
        "manifest_path": manifest_path,
        "state_dir": state_dir if state_dir is not None else paths.state_dir(values),
        "uid": uid,
    }
    if name == "systemd":
        return SystemdBackend(**kwargs)  # type: ignore[arg-type]
    return LaunchdBackend(**kwargs)  # type: ignore[arg-type]


__all__ = [
    "BACKEND_NAMES",
    "CREATE",
    "DELETE",
    "GENERATED_HEADER",
    "UNCHANGED",
    "UPDATE",
    "Backend",
    "FileChange",
    "HealthCheck",
    "ReconcilePlan",
    "create",
    "default_backend_name",
    "unified_diff",
]
